TEKKEN_WEB/areas/Admin/Controllers/DumpDataController.cs
using Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System.Collections.Generic;
using System.Threading.Tasks;
using TEKKEN_WEB.areas.Admin.Controllers;
using TEKKEN_WEB.Enums;
using TEKKEN_WEB.Models;

namespace TEKKEN_WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DumpDataController : BaseCharacterController
    {
        private IMoveRepository _moveRepository;
        private IMoveDataRepository _moveDataRepository;
        private IHitTypeRepository _hitTypeRepository;
        private IMoveTypeRepository _moveTypeRepository;
        private IMoveSubTypeRepository _moveSubTypeRepository;
        private IDumpDataRepository _dumpDataRepository;

        public DumpDataController(
            IStringLocalizer<SharedResource> sharedLocalizer,
            ICharacterRepository characterRepository,
            IMoveRepository moveRepository,
            IMoveDataRepository moveDataRepository,
            IMoveTypeRepository moveTypeRepository,
            IMoveSubTypeRepository moveSubTypeRepository,
            ITranslateNameRepository translateNameRepository,
            IDumpDataRepository dumpDataRepository,

            IHitTypeRepository hitTypeRepository) : base(sharedLocalizer, translateNameRepository, moveDataRepository, characterRepository)
        {
            _moveDataRepository = moveDataRepository;
            _hitTypeRepository = hitTypeRepository;
            _moveTypeRepository = moveTypeRepository;
            _moveSubTypeRepository = moveSubTypeRepository;
            Initialize(TableName.move);
            TitleDescription = TableName.move_Data.ToString();
            _translateNameRepository.SetTable(TableName.move, TableName.move_Data);
            _moveDataRepository.SetTable(tableName);
            _dumpDataRepository = dumpDataRepository;
            _moveRepository = moveRepository;
        }

        [HttpGet]
        public override IActionResult Index(int character_code = 18, int movePosition = -1)
        {
            ViewBag.tableName = tableName;
            ViewBag.TitleDescription = TitleDescription;
            ViewBag.AllList = _dumpDataRepository.GetAllList( character_code);
            ViewBag.baseType = baseType;
            ViewBag.character_code = character_code;
            ViewBag.SelectAllCharacters = _characterRepository.GetAllCharactersSelectItems(character_code);
            ViewBag.subTableName = TableName.move_Data;
            UpdateMoveData(character_code);
            return View();
        }


        [HttpGet]
        public IActionResult CreateMove(int character_code)
        {
            List<DumpData> dumpData=_dumpDataRepository.GetAllList(character_code);
            foreach (DumpData data in dumpData) {
                _moveRepository.SetTable(TableName.move);
                BaseModel baseModel = new BaseModel();
                
                baseModel.Number = data.Number;
                baseModel.Description = data.Description;
                baseModel.Character_code = data.Character_code;
                _moveRepository.Create(baseModel);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateMoveData(int character_code)
        {
            List<DumpData> dumpData = _dumpDataRepository.GetAllList(character_code);
            foreach (DumpData data in dumpData)
            {
                _moveRepository.SetTable(TableName.move);
                MoveData moveData = new MoveData();

                //int number = data.Number;
                moveData.Code= _moveRepository.Move_GetCodeByNumber(character_code, data.Number);
                
                moveData.MoveType_code = data.MoveType_code;
                moveData.MoveSubType_code = data.MoveSubType_code;

                moveData.HitCount = data.HitCount;
                moveData.HitLevel = data.HitLevel;
                moveData.Damage = data.Damage;

                moveData.StartFrame = data.StartFrame;
                //moveData.SecondFrame = data.SecondFrame;
                moveData.StartType_code = data.StartType_code;

                moveData.GuardFrame = data.GuardFrame;
                moveData.GuardType_code = data.GuardType_code;

                moveData.HitFrame = data.HitFrame;
                moveData.HitType_code = data.HitType_code;

                moveData.CounterFrame = data.CounterFrame;
                moveData.CounterType_code = data.CounterType_code;

                moveData.BreakThrow = data.BreakThrow;
                moveData.AfterBreak = data.AfterBreak;

                moveData.Homing = false;
                moveData.PowerCrush = false;
                moveData.TechnicallyCrouching = false;
                moveData.TechnicallyJumping = false;
                moveData.TailSpin = false;
                moveData.WallSplat = false;

                _moveDataRepository.Merge(moveData);
            }


            //@Move_Code
            return RedirectToAction("Index", new { character_code = character_code }); // 저장 후 리스트 페이지로 이동
        }

        //[HttpGet]
        //public IActionResult UpdateMoveData(int id, int character_code)
        //{
        //    ViewBag.FormType = FormType.Update;
        //    ViewBag.readonly_Id = "readonly=\"readonly\"";
        //    ViewBag.TitleDescription = "기술명 수정 - 아래 항목을 수정하세요.";
        //    ViewBag.SaveButtonText = "저장";
        //    //BaseModel baseModel = _moveDataRepository.GetDetailBaseModelById (id);
        //    MoveData moveData = _moveDataRepository.GetMoveDataById(id);
        //    ViewBag.tableName = TableName.move;
        //    ViewBag.subTableName = TableName.move_Data;
        //    //_hitTypeRepository.SetTable(TableName.HitType);
        //    ViewBag.SelectHitTypes = _hitTypeRepository.GetSelectList();
        //    ViewBag.SelectMoveSubTypes = _moveSubTypeRepository.GetSelectListByCharacter(character_code);
        //    ViewBag.SelectMoveTypes = _moveTypeRepository.GetSelectList(character_code);
        //    return View(moveData);
        //}

    }
}

TEKKEN_WEB/areas/Admin/Controllers/HitTypeController.cs
using Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using TEKKEN_WEB.areas.Admin.Controllers;
using TEKKEN_WEB.Enums;


namespace TEKKEN_WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HitTypeController : BaseDefaultController
    {
        private IHitTypeRepository _hitTypeRepository;

        public HitTypeController(IStringLocalizer<SharedResource> sharedLocalizer,
                                IHitTypeRepository hitTypeRepository,
                                ITranslateNameRepository translateNameRepository,
                                IBaseDefaultRepository baseDefaultRepository) : base(sharedLocalizer, translateNameRepository, baseDefaultRepository)
        {
            _hitTypeRepository = hitTypeRepository;
            _hitTypeRepository.SetTable(tableName);
            Initialize(TableName.HitType);
        }
    }
}

TEKKEN_WEB/areas/Admin/Controllers/MoveController.cs
using Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using TEKKEN_WEB.areas.Admin.Controllers;
using TEKKEN_WEB.Enums;


namespace TEKKEN_WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MoveController : BaseCharacterController
    {
        private IMoveRepository _moveRepository;

        public MoveController(
            IStringLocalizer<SharedResource> sharedLocalizer,
                                ICharacterRepository characterRepository,
                                IMoveRepository moveRepository,
                                ITranslateNameRepository translateNameRepository) : base(sharedLocalizer, translateNameRepository, moveRepository, characterRepository)
        {
            _moveRepository = moveRepository;
            Initialize(TableName.move);

        }

        /// <summary>
        /// 기술목록 페이지
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult SelectMove(string stateType, int character_code)
        {
            ViewBag.stateType = stateType;
            ViewBag.SelectMoves = _moveRepository.GetSelectListByCharacter(character_code);
            return PartialView("_SelectMoveModalPartial");
        }

    }
}

TEKKEN_WEB/areas/Admin/Controllers/StateController.cs
using Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using TEKKEN_WEB.areas.Admin.Controllers;
using TEKKEN_WEB.Enums;


namespace TEKKEN_WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StateController : BaseStateGroupController
    {
        private IStateRepository _stateRepository;
        private IStateGroupRepository _stateGroupRepository;

        public StateController(IStringLocalizer<SharedResource> sharedLocalizer,
            IStateGroupRepository stateGroupRepository,
            IStateRepository stateRepository,
            ITranslateNameRepository translateNameRepository,
            IBaseStateGroupRepository baseStateGroupRepository) : base(sharedLocalizer, translateNameRepository, baseStateGroupRepository, stateGroupRepository)
        {
            _stateGroupRepository = stateGroupRepository;
            _stateRepository = stateRepository;
            Initialize(TableName.State);
        }


        public JsonResult GetStates(int stateGroup_Code)
        {
            return Json(_stateRepository.GetStateByGroupSelectItems(stateGroup_Code));
        }
    }
}

TEKKEN_WEB/areas/Admin/Views/Shared/Create.cshtml
@model BaseModel

@{
    Layout = "_Layout";
}

<h2 style="text-align:center;">MOVE</h2>

<hr />

<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            @await Html.PartialAsync("_EditForm")
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

TEKKEN_WEB/areas/Admin/Views/Shared/Update.cshtml
@model BaseModel

@{
    Layout = "_Layout";
}

<h2 style="text-align:center;">@ViewBag.TitleDescription</h2>

<hr />

<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-action="Update"
              enctype="multipart/form-data" method="post">
            @await Html.PartialAsync("_EditForm")
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

TEKKEN_WEB/areas/Admin/Views/Shared/UpdateAllName.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center;">@ViewBag.TitleDescription</h2>

<hr />

<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-action="UpdateAllName"
              enctype="multipart/form-data" method="post">
                @await Html.PartialAsync("_AllNameEditForm")
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script type="text/javascript" src="~/js/translateName.js"></script>
}

TEKKEN_WEB/areas/Admin/Views/Shared/UpdateName.cshtml
@{
    Layout = "_Layout";
}

<h2 style="text-align:center;">@ViewBag.TitleDescription</h2>

<hr />

<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-action="UpdateName"
              enctype="multipart/form-data" method="post">
            @await Html.PartialAsync("_NameEditForm")
        </form>
    </div>
</div>


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

TEKKEN_WEB/areas/Admin/Views/Shared/_AllNameEditForm.cshtml
@model TranslateName[]
@using TEKKEN_WEB.Enums


<div class="row mb-3">
    <div class="col-3">
        <label class="col-form-label col-form-label-sm">코드</label>
    </div>
    <div class="col-9">
        <input type="text" class="form-control form-control-sm" value="@ViewBag.baseModel.Code" placeholder="col-form-label-sm" readonly="readonly">
    </div>
</div>

<div class="row mb-3">
    <div class="col-3">
        <label class="col-form-label col-form-label-sm">명칭</label>
    </div>
    <div class="col">
        <input type="text" class="form-control form-control-sm" value="@ViewBag.baseModel.Description" placeholder="col-form-label-sm" readonly="readonly">
    </div>
</div>
<br />


@{int i = 0; }
@foreach (var item in @ViewBag.translateNames)
{
<div class="row mb-1">
    <div class="col-1">
        <label asp-for="@Model[i].Code" class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col-2">
        <input asp-for="@Model[i].Code" class="form-control form-control-sm" value="@item.Code" readonly="readonly" />
    </div>

    <div class="col-1">
        <label asp-for="@Model[i].Id" class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col-2">
        <input asp-for="@Model[i].Id" class="form-control form-control-sm" value="@item.Id" readonly="readonly" />
    </div>
    <div class="col-1">
        <label class="col-form-label col-form-label-sm">Language</label>
    </div>
    <div class="col-2">
        <input asp-for="@Model[i].Language_Code" class="form-control col-form-label-sm" value="@item.Language_Code" readonly="readonly" />
    </div>

    <div class="col text-right">
        <div class="form-check">
            <input id="@String.Format("Change_{0}", @item.Language_Code)" asp-for="@Model[i].Change" class="form-check-input" type="checkbox">
            <label class="form-check-label" for="flexCheckChecked">
                Modified
            </label>
        </div>
    </div>
</div>
    <div class="row mb-1">
        <div class="col-1">
            <label class="col-form-label col-form-label-sm">AsIs</label>
        </div>
        <div class="col-11">
            <input type="text" class="form-control form-control-sm" value="@item.Name" placeholder="col-form-label-sm" readonly="readonly">
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-1">
            <label class="col-form-label col-form-label-sm">ToBe</label>
        </div>
        <div class="col-11">
            <input id="@String.Format("TlanslatedCommand_{0}", @item.Language_Code)" language_Code="@item.Language_Code" asp-for="@Model[i].Name" type="text" class="form-control form-control-sm commandName" placeholder="col-form-label-sm" value="@item.Name" />
        </div>
    </div>
    i++;
}


<div class="row">
    <div class="col-sm-3">
        <input type="submit" value="@ViewBag.SaveButtonText" class="btn btn-primary" />
        <div class="col-sm-3">
        </div>
        <a asp-action="Index" class="btn btn-default" asp-route-character_code="@ViewBag.Character_Code">리스트</a>
    </div>
   
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <span class="text-danger">@ViewBag.ErrorMessage</span>
</div>

TEKKEN_WEB/areas/Admin/Views/Shared/_CharacterSelect.cshtml
@model Character
@{
}

@*==================== 캐릭터 코드 ====================*@
<div class="row mb-3">
    <div class="col-sm-2">
        <label class="col-form-label col-form-label-sm">캐릭터</label> 
    </div>
    <div class="col-sm">
        <select id="Character" asp-items="@ViewBag.SelectAllCharacters "></select>
        @*<input asp-for="Character_code" type="text" class="form-control form-control-sm" id="colFormLabelSm" placeholder="col-form-label-sm" readonly="readonly">*@
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @*<script type="text/javascript" src="~/js/moveSubType.js"></script>*@

    @*<script>
        $('#Character').change(function () {
            var url = '/Admin/MoveSubType/Index';
            var character_code = $('#Character').val();
            location.href = url + '?Character_code=' + character_code;
        });

        $().ready(function () {
            $('#Character').focus();
        });
    </script>*@
}

TEKKEN_WEB/areas/Admin/Views/Shared/_EditForm.cshtml
@model BaseModel
@using TEKKEN_WEB.Enums

@if (ViewBag.FormType == FormType.Update)
{
    <div class="row mb-3">
        <div class="col-sm-2">
            <label asp-for="Id" class=" control-label">ID</label>
        </div>
        <div class="col-sm">
            <input asp-for="Id" class="form-control" style="border:0; width:100px;" maxlength="10" readonly="readonly" />
            @*<input type="hidden" name="id" value="@Model.Id" />*@
        </div>
    </div>

    @*====================  코드 ====================*@
    <div class="row mb-3">
        <div class="col-sm-2">
            <label asp-for="Code" class="col-form-label col-form-label-sm"></label>
        </div>
        <div class="col-sm">
            <input asp-for="Code" type="text" class="form-control form-control-sm" placeholder="@Model.Code" readonly="readonly">
        </div>
    </div>
}
@*==================== 순번 ====================*@
<div class="row mb-3">
    <div class="col-sm-2">
        <label asp-for="Number" class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col-sm">
        <input asp-for="Number" type="text" class="form-control form-control-sm" placeholder="col-form-label-sm">
    </div>
</div>
@if (ViewBag.baseType == BaseType.StateGroup_Code)
{

    @*==================== 하위 그룹 분류명 ====================*@
    <div class="row mb-3">
        <div class="col-sm-2">
            <label asp-for="StateGroup_code" class="col-form-label col-form-label-sm"></label>
        </div>
        <div class="col-sm">
            <input asp-for="StateGroup_code" type="text" class="form-control form-control-sm" placeholder="번역 기술명 입력" readonly="readonly">
        </div>
    </div>
}
@*==================== 캐릭터 코드 ====================*@
@if (ViewBag.baseType == BaseType.Character_Code)
{

    <div class="row mb-3">
        <div class="col-sm-2">
            <label asp-for="Character_code" class="col-form-label col-form-label-sm"></label>
        </div>
        <div class="col-sm">
            <input asp-for="Character_code" class="col-form-label col-form-label-sm" readonly="readonly">
        </div>
    </div>
}

@*==================== 하위 분류명 ====================*@
<div class="row mb-3">
    <div class="col-sm-2">
        <label asp-for="Description" class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col-sm">
        <input id="Description" asp-for="Description" type="text" class="form-control form-control-sm" placeholder="번역 기술명 입력">
    </div>
</div>


<div class="row">
    <div class="col-sm-10">
        <input type="submit" value="@ViewBag.SaveButtonText"
               class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-default">리스트</a>
    </div>
    <div class="col-sm">
        @if (ViewBag.baseType == BaseType.Character_Code)
        {
            <a asp-action="Delete" class="btn btn-primary text-right" asp-route-id="@Model.Id" asp-route-character_code="@Model.Character_code" onclick="return confirm('정말 삭제하겠습니까?');">삭제</a>
        }
        else if (ViewBag.baseType == BaseType.StateGroup_Code)
        {
            <a asp-action="Delete" class="btn btn-primary text-right" asp-route-id="@Model.Id" asp-route-StateGroup_code="@Model.StateGroup_code" onclick="return confirm('정말 삭제하겠습니까?');">삭제</a>
        }
        else { 
    <a asp-action="Delete" class="btn btn-primary text-right" asp-route-id="@Model.Id" onclick="return confirm('정말 삭제하겠습니까?');">삭제</a>
        }


    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <span class="text-danger">@ViewBag.ErrorMessage</span>
</div>

TEKKEN_WEB/areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ADMIN</title>

    <environment name="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment name="Staging, Production">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ADMIN</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="user"
                               asp-controller="MoveList"
                               asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="TekkenVersion"
                               asp-action="Index">버전</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="Character"
                               asp-action="Index">캐릭터</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="Move"
                               asp-action="Index">Move</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="MoveCommand"
                               asp-action="Index">MoveCommand</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="MoveData"
                               asp-action="Index">MoveData</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="MoveType"
                               asp-action="Index">MoveType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="MoveSubType"
                               asp-action="Index">MoveSubType</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="MoveText"
                               asp-action="Index">MoveText</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="State"
                               asp-action="Index">State</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="StateGroup"
                               asp-action="Index">StateGroups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="HitType"
                               asp-action="Index">HitType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area="Admin"
                               asp-controller="DumpData"
                               asp-action="Index">DumpData</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="row">
            <div class="col-md-6">
                <p>&copy; @System.DateTime.Now.Year - Localization</p>
            </div>
            <div class="col-md-6 text-right">
                @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </div>
        <div class="container">
            &copy; 2020 - TEKKEN_WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment name="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment name="Staging, Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.JQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.3.1/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.JQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
    @RenderSection("Scripts2", required: false)
    @*@await RenderSectionAsync("Scripts", required: false)*@
</body>
</html>

TEKKEN_WEB/areas/Admin/Views/Shared/_NameEditForm.cshtml
@model TranslateName
@using TEKKEN_WEB.Enums
@if (ViewBag.FormType == FormType.Update)
{
    <div class="row mb-3">
        <div class="col-sm-2">
            <label asp-for="Id" class=" control-label">ID</label>
        </div>
        <div class="col-sm">
            <input asp-for="Id" class="form-control" style="border:0; " maxlength="10" readonly="readonly" />
        </div>
    </div>

}

<div class="row mb-3">
    <div class="col-sm-2">
        <label asp-for="TableName" class="control-label"></label>
    </div>
    <div class="col-sm">
        <input asp-for="TableName" class="form-control" style="width:150px;" minlength="2" readonly="readonly" />
        <span asp-validation-for="TableName" class="text-danger"></span>
    </div>
</div>


<div class="row mb-3">
    <div class="col-sm-2">
        <label asp-for="Code" class="control-label"></label>
    </div>
    <div class="col-sm">
        <input asp-for="Code" class="form-control" style="width:150px;"  minlength="8" maxlength="9" readonly="readonly" />
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-2">
        <label asp-for="Language_Code" class="control-label"></label>
    </div>
    <div class="col-sm">
        <input asp-for="Language_Code" class="form-control" style="width:150px;" minlength="2" maxlength="9" readonly="readonly" />
        <span asp-validation-for="Language_Code" class="text-danger"></span>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-2">
        <label asp-for="Description" class="control-label"></label>
    </div>
    <div class="col-sm">
        <input asp-for="Description" class="form-control" style="width:150px;" readonly="readonly" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-2">
        <label asp-for="Name" class="control-label"></label>
    </div>
    <div class="col-sm">
        <input asp-for="Name" class="form-control" style="width:150px;" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-2">
        <input type="submit" value="@ViewBag.SaveButtonText" class="btn btn-primary" />
    </div>

    <div class="col-sm">
        <a asp-action="Index" class="btn btn-default">리스트</a>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <span class="text-danger">@ViewBag.ErrorMessage</span>
    </div>
</div>