TEKKEN_WEB/areas/Admin/Models/StateGroup.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TEKKEN_WEB.Models
{
    public class StateGroup : BaseModel
    {
        }
}

TEKKEN_WEB/areas/Admin/Models/StateGroup/IStateGroupRepository.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TEKKEN_WEB.Models;

namespace Admin.Models
{
    public interface IStateGroupRepository : IBaseRepository
    {
        List<StateGroup> GetStateGroups();

        List<SelectListItem> GetStateGroupsSelectItems(int stateGroup_code);

        //StateGroup GetStateGroup_DetailById(int id);

        //StateGroup GetStateGroup_LastDetail();

        //void Create(StateGroup stateGroup);

        //void Update(StateGroup stateGroup);

        //void Delete(int code);
    }
}

TEKKEN_WEB/areas/Admin/Models/StateGroup/StateGroupRepository.cs
using Admin.Models;
using Dapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using TEKKEN_WEB.Enums;
using TEKKEN_WEB.Models;

namespace Admin.Models
{
    public class StateGroupRepository : BaseStateGroupRepository, IStateGroupRepository
    {
        private IConfiguration _config;
        private SqlConnection con;
        private ILogger<StateGroupRepository> _logger;
        public string language_code = string.Empty;


        public StateGroupRepository(IConfiguration config, ILogger<StateGroupRepository> logger, IHttpContextAccessor httpContextAccessor) : base(config, logger, httpContextAccessor)
        {
            _config = config;
            mainTable = TableName.StateGroup;
            con = new SqlConnection(_config.GetSection("ConnectionStrings").GetSection("TekkenConnection").Value);
            _logger = logger;
            language_code = httpContextAccessor.HttpContext.Features.Get<IRequestCultureFeature>().RequestCulture.Culture.TwoLetterISOLanguageName;
        }


        public List<StateGroup> GetStateGroups() => con.Query<StateGroup>("[StateGroup_GetStateGroups]", new { language_code = language_code }, commandType: CommandType.StoredProcedure).ToList();

        public List<SelectListItem> GetStateGroupsSelectItems(int stateGroup_code = 1)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (StateGroup stateGroups in GetStateGroups())
            {
                bool selectedItem = false;
                if (stateGroups.Code == stateGroup_code)
                {
                    selectedItem = true;
                }
                list.Add(new SelectListItem { Text = stateGroups.Name, Value = stateGroups.Code.ToString(), Selected = selectedItem });
            }
            return list;
        }
        /*
        public StateGroup GetStateGroup_LastDetail() => con.Query<StateGroup>("[COMMON_GetlastDetail]",
            new DynamicParameters(new { tableName = TableName.StateGroup.ToString()}),
                commandType: CommandType.StoredProcedure).SingleOrDefault();
        */
        /*
        public void Create(StateGroup stateGroup)
        {
            _logger.LogInformation("데이터 입력");
            try
            {
                SaveOrUpdate(stateGroup, FormType.Create);
            }
            catch (System.Exception ex)
            {
                _logger.LogError("데이터 입력 에러: " + ex);
            }
        }

        public void Update(StateGroup stateGroup)
        {
            _logger.LogInformation("데이터 수정");
            try
            {
                SaveOrUpdate(stateGroup, FormType.Update);
            }
            catch (System.Exception ex)
            {
                _logger.LogError("데이터 수정 에러: " + ex);
            }
        }*/
        /*
        /// <summary>
        /// 데이터 저장, 수정, 답변 공통 메서드
        /// </summary>
        protected override int SaveOrUpdate(BaseModel baseModel, FormType formType)
        {
            int result = 0;
            /*
            var parameters = new DynamicParameters();

            parameters.Add("@number", value: stateGroup.Number, dbType: DbType.Int16);
            parameters.Add("@description", value: stateGroup.Description, dbType: DbType.String);

            switch (formType)
            {
                case FormType.Create:
                    result = con.Execute("[stateGroup_CreateStateGroup]", parameters
                        , commandType: CommandType.StoredProcedure);
                    break;

                case FormType.Update:
                    parameters.Add("@Id", value: stateGroup.Id, dbType: DbType.Int32);

                    result = con.Execute("[stateGroup_UpdateStateGroup]", parameters,
                        commandType: CommandType.StoredProcedure);
                    break;
            }
            return result;
        }

        public StateGroup GetStateGroup_DetailById(int id)
         => con.Query<StateGroup>("[StateGroup_GetDetailById]",
                new DynamicParameters(new { id = id, language_code = language_code }),
                commandType: CommandType.StoredProcedure).SingleOrDefault();


        
public void Delete(int code) =>
   con.Execute("[COMMON_DeleteItem]",
       new { tableName = TableName.StateGroup.ToString(), code = code },
       commandType: CommandType.StoredProcedure);*/
    }
}

TEKKEN_WEB/areas/Admin/Controllers/StateGroupController.cs
using Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using TEKKEN_WEB.areas.Admin.Controllers;
using TEKKEN_WEB.Enums;
using TEKKEN_WEB.Models;


namespace TEKKEN_WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StateGroupController : BaseDefaultController
    {
        private IStateGroupRepository _stateGroupRepository;

        public StateGroupController(IStringLocalizer<SharedResource> sharedLocalizer,
            IStateGroupRepository stateGroupRepository,
            ITranslateNameRepository translateNameRepository,
            IBaseDefaultRepository baseDefaultRepository) : base(sharedLocalizer, translateNameRepository, baseDefaultRepository)
        {
            _stateGroupRepository = stateGroupRepository;
            _translateNameRepository.SetTable(tableName);
            Initialize(TableName.StateGroup);
            _stateGroupRepository.SetTable(tableName);
            
        }

        //public IActionResult Index()
        //{
        //    ViewBag.tableName = tableName;
        //    ViewBag.TitleDescription = "StateGroup";
        //    ViewBag.AllList = _stateGroupRepository.GetStateGroups();
        //    return View();
        //}

        //[HttpGet]
        //public IActionResult Create()
        //{
        //    ViewBag.FormType = FormType.Create;
        //    BaseModel baseModel = _stateGroupRepository.GetRecentBaseModel();
        //    //ViewBag.SelectAllCharacters = _characterRepository.GetAllCharactersSelectItems();

        //    ViewBag.TitleDescription = "StateGroup 추가 - 다음 필드들을 채워주세요.";
        //    ViewBag.SaveButtonText = "저장";

        //    return View(baseModel);
        //}

        /*
        [HttpPost]
        public async Task<IActionResult> Create(StateGroup stateGroup)
        {
            _stateGroupRepository.Create(stateGroup); // 데이터 저장
            //// 데이터 저장 후 리스트 페이지 이동시 toastr로 메시지 출력
            //TempData["Message"] = "데이터가 저장되었습니다.";
            return RedirectToAction("Index", stateGroup); // 저장 후 리스트 페이지로 이동
        }

        /// <summary>
        /// 기술 하위 분류 수정 폼
        /// <param name="id">id</param>
        /// </summary>
        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewBag.FormType = FormType.Update;
            ViewBag.TitleDescription = "기술 하위 분류 수정 - 아래 항목을 수정하세요.";
            ViewBag.SaveButtonText = "수정";
            StateGroup stateGroup = _stateGroupRepository.GetStateGroup_DetailById(id);
            
            return View(stateGroup);
        }

        /// <summary>
        /// 기술 하위 분류 저장
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Update(StateGroup stateGroup)
        {
            _stateGroupRepository.Update(stateGroup); // 데이터 저장
            return RedirectToAction("Index", stateGroup); // 저장 후 리스트 페이지로 이동

        }

        ///// <summary>
        ///// 기술 하위 분류 수정 폼
        ///// <param name="code">code</param>
        ///// </summary>
        //[HttpGet]
        //public IActionResult UpdateName(int code)
        //{
        //    ViewBag.FormType = FormType.Update;
        //    ViewBag.TitleDescription = "기술 하위 분류명 수정 - 아래 항목을 수정하세요.";
        //    ViewBag.SaveButtonText = "수정";
        //    TranslateName translateName = _translateNameRepository.GetTranslateNameByCode(code, TableName.StateGroup);

        //    return View(translateName);
        //}


        //[HttpPost]
        //public async Task<IActionResult> UpdateName(TranslateName translateName)
        //{
        //    translateName.TableName = TableName.StateGroup;
        //    _translateNameRepository.Update(translateName); // 데이터 저장
        //    return RedirectToAction("Index", translateName); // 저장 후 리스트 페이지로 이동
        //}

        [HttpGet]
        public async Task<IActionResult> Delete(int code)
        {
            _stateGroupRepository.Delete(code);
            return RedirectToAction("Index"); // 저장 후 리스트 페이지로 이동
        }
        */
    }
}

TEKKEN_WEB/areas/Admin/Views/StateGroup/Create.cshtml
@model BaseModel

@{
    Layout = "_Layout";
}

<h2 style="text-align:center;">StateGroup</h2>
@ViewBag.TitleDescription
<hr />

<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-controller="StateGroup" asp-action="Create"
              enctype="multipart/form-data" method="post">
            @await Html.PartialAsync("_EditForm")
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

TEKKEN_WEB/areas/Admin/Views/StateGroup/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    .table tbody tr:nth-child(4n-3) {
        background: #e2e2e2;
    }
</style>

<div class="container">
        @await Html.PartialAsync("_ListViewForm")
</div>

TEKKEN_WEB/areas/Admin/Views/StateGroup/Index2.cshtml
@inject IStateGroupRepository stateGroupRepository
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["StateGroup"] = "StateGroup";
}

<div class="container">
    <div class="m-auto" id="Character-list">
        <h2 style="text-align:center;">StateGroup</h2>
        <span style="color: #ff0000">=================</span>

        <hr />
        @ViewData["StateGroup"]
        <div class="table-responsive">
            <table class="table table-bordered table-hover" style="width: 100%; margin-left: auto; margin-right: auto; border: 0;">
                <colgroup>
                    <col style="width: 100px;" />
                    <col style="width: 100px;" />
                    <col style="width: 150px;" />
                </colgroup>
                <thead>
                    <tr>
                        <th>@SharedLocalizer["ID"]</th>
                        <th>@SharedLocalizer["Code"]</th>
                        <th>@SharedLocalizer["Description"]</th>
                        <th>@SharedLocalizer["Name"]</th>
                        <th>@SharedLocalizer["Number"]</th>
                        <th>@SharedLocalizer["Modify"]</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in stateGroupRepository.GetStateGroups())
                    {
                    <tr>
                        <td>
                            <a area="Admin" asp-controller="Character" asp-action="Details" asp-route-code="@item.Code">
                                @Html.Raw(@item.Id)
                            </a>
                        </td>
                        <td>
                            @Html.Raw(@item.Code)
                        </td>
                        <td>
                            @Html.Raw(@item.Description)
                        </td>
                        <td>
                            @Html.Raw(@item.Name)
                        </td>
                        <td>
                            @Html.Raw(@item.Number)
                        </td>
                        <td>
                            <a asp-action="Update" class="btn btn-primary" asp-route-id="@item.Id">수정</a>
                            <a asp-action="UpdateName" class="btn btn-primary" asp-route-code="@item.Code">명칭 편집</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
        <a asp-action="Create" class="btn btn-primary">추가</a>
    </div>
</div>

TEKKEN_WEB/areas/Admin/Views/StateGroup/UpdateAllName.cshtml
@model StateGroup

@{
    Layout = "_Layout";
}

<h2 style="text-align:center;">StateGroup</h2>
@ViewBag.TitleDescription
<hr />

@*<div class="row">*@
<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-controller="StateGroup" asp-action="UpdateAllName"
              enctype="multipart/form-data" method="post">
            @await Html.PartialAsync("_AllNameEditForm")
        </form>
    </div>
</div>

@*<select asp-for="Code" asp-items="@ViewBag.SelectMoveType "></select>*@



@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script type="text/javascript" src="~/js/translateName.js"></script>
}

TEKKEN_WEB/areas/Admin/Views/StateGroup/UpdateName.cshtml
@{
    Layout = "_Layout";
}

<h2 style="text-align:center;">StateGroup</h2>
@ViewBag.TitleDescription
<hr />

@*<div class="row">*@
<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-controller="StateGroup" asp-action="UpdateName"
              enctype="multipart/form-data" method="post">
            @await Html.PartialAsync("_NameEditForm")
        </form>
    </div>
</div>

@*<select asp-for="Code" asp-items="@ViewBag.SelectMoveType "></select>*@


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}