TEKKEN_WEB/areas/Admin/Models/MoveCommand.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TEKKEN_WEB.Models
{
    public class MoveCommand : BaseModel
    {
        [Display(Name = "기술명")]
        [DataType(DataType.Text)]
        //[Required(ErrorMessage = "기술명을 입력해 주세요.")]
        public string Move_Name { get; set; }

        [Display(Name = "커맨드")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "커맨드를 입력해 주세요.")]
        public string Command { get; set; }

 
        [Display(Name = "변경")]
        public bool Change { get; set; }

    }
}

TEKKEN_WEB/areas/Admin/Models/MoveCommand/IMoveCommandRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TEKKEN_WEB.Enums;
using TEKKEN_WEB.Models;

namespace Admin.Models
{
    public interface IMoveCommandRepository : IBaseCharacterRepository
    {
        public List<MoveCommand> GetAllList(BaseType baseType, int character_code);
        public List<MoveCommand> GetMoveCommandById(int Id);

        public void Merge(MoveCommand moveCommand);
        public void UpdateMoveCommandName(MoveCommand[] moveCommand);
    }
}

TEKKEN_WEB/areas/Admin/Models/MoveCommand/MoveCommandRepository.cs
using Dapper;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using TEKKEN_WEB.Enums;
using TEKKEN_WEB.Models;

namespace Admin.Models
{
    public class MoveCommandRepository : BaseCharacterRepository, IMoveCommandRepository
    {
        private ITranslateNameRepository _translateNameRepository;

        public MoveCommandRepository(IConfiguration config, ILogger<MoveCommandRepository> logger,
            IHttpContextAccessor httpContextAccessor, ITranslateNameRepository translateNameRepository) : base(config, logger, httpContextAccessor)
        {
            _logger = logger;
            con = new SqlConnection(_config.GetSection("ConnectionStrings").GetSection("TekkenConnection").Value);
            _translateNameRepository = translateNameRepository;
        }

        public List<MoveCommand> GetAllList(BaseType baseType, int character_code) => con.Query<MoveCommand>("[MoveCommand_GetAllList]", new { character_code = character_code }, commandType: CommandType.StoredProcedure).ToList();

        public List<MoveCommand> GetMoveCommandById(int id) => con.Query<MoveCommand>("[MoveCommand_GetMoveCommandById]", new { id = id }, commandType: CommandType.StoredProcedure).ToList();



        public void Merge(MoveCommand moveCommand)
        {
            _logger.LogInformation("데이터 입력");
            try
            {
                SaveOrUpdate(moveCommand, FormType.Create);
            }
            catch (System.Exception ex)
            {
                _logger.LogError("데이터 입력 에러: " + ex);
            }
        }

        /// <summary>
        /// 데이터 저장, 수정, 답변 공통 메서드
        /// </summary>
        public int SaveOrUpdate(MoveCommand moveCommand, FormType formType)
        {
            int result = 0;
            var parameters = new DynamicParameters();

            parameters.Add("@Id", value: moveCommand.Id, dbType: DbType.Int32);
            parameters.Add("@code", value: moveCommand.Code, dbType: DbType.Int32);
            parameters.Add("@Command", value: moveCommand.Command, dbType: DbType.String);


            result = con.Execute("[moveCommand_Merge]", parameters, commandType: CommandType.StoredProcedure);
            return result;
        }




        public void UpdateMoveCommandName(MoveCommand[] moveCommand)
        {
            _logger.LogInformation("데이터 수정");
            try
            {
                foreach (MoveCommand mv in moveCommand)
                {
                    if (mv.Change == true)
                    {
                        TranslateName translateName = new TranslateName();
                        translateName.Id = mv.Id;
                        translateName.TableName = TableName.move_Command;
                        translateName.Name = mv.Name;
                        _translateNameRepository.Update(translateName); // 데이터 저장
                        //new TekkenCommand(move.Command, "en").CreateForeignCommand(move.Code);
                        //new TekkenCommand(move.Command, "ko").CreateForeignCommand(move.Code);

                    }
                }


            }
            catch (System.Exception ex)
            {
                _logger.LogError("데이터 수정 에러: " + ex);
            }
            //return RedirectToAction("Index", translateName); // 저장 후 리스트 페이지로 이동
        }
        /*
      public List<SelectListItem> GetMovesByCharacterSelectItems(int character_code)
      {
          List<SelectListItem> list = new List<SelectListItem>();
          foreach (Move move in GetAllMoves(character_code))
          {
              list.Add(new SelectListItem { Text = move.Name, Value = move.Code.ToString() });
          }
          return list;
      }*/

    }
}

TEKKEN_WEB/areas/Admin/Controllers/MoveCommandController.cs
using Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System;
using System.Threading.Tasks;
using TEKKEN_WEB.areas.Admin.Controllers;
using TEKKEN_WEB.COMMON.Command;
using TEKKEN_WEB.Enums;
using TEKKEN_WEB.Models;

namespace TEKKEN_WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MoveCommandController : BaseCharacterController
    {
        private IMoveCommandRepository _moveCommandRepository;
        private IStateRepository _stateRepository;
        private IStateGroupRepository _stateGroupRepository;

        public MoveCommandController(
            IStringLocalizer<SharedResource> sharedLocalizer,
            ICharacterRepository characterRepository,
            IMoveCommandRepository moveCommandRepository,
            IStateRepository stateRepository,
            IStateGroupRepository stateGroupRepository,
            ITranslateNameRepository translateNameRepository) : base(sharedLocalizer, translateNameRepository, moveCommandRepository, characterRepository)
        {
            _moveCommandRepository = moveCommandRepository;
            _stateRepository = stateRepository;
            _stateGroupRepository = stateGroupRepository;

            Initialize(TableName.move);
            TitleDescription = TableName.move_Command.ToString();
            _translateNameRepository.SetTable(TableName.move, TableName.move_Command);
            _moveCommandRepository.SetTable(tableName);
        }

        [HttpGet]
        public override IActionResult Index(int character_code = 1, int movePosition = -1)
        {
            ViewBag.tableName = tableName;
            ViewBag.TitleDescription = TitleDescription;
            ViewBag.AllList = _moveCommandRepository.GetAllList(baseType, character_code);
            ViewBag.baseType = baseType;
            ViewBag.character_code = character_code;
            ViewBag.movePosition = movePosition;
            ViewBag.SelectAllCharacters = _characterRepository.GetAllCharactersSelectItems(character_code);
            ViewBag.subTableName = TableName.move_Command;
            //ViewBag.AllList = _moveTypeRepository.GetAllMoveTypes();
            //ViewBag.SelectAllStateGroups = _stateGroupRepository.GetStateGroupsSelectItems(0);
            //ViewBag.SelectAllStateGroups = _stateGroupRepository.GetStateGroupsSelectItems();


            return View();
        }

        [HttpGet]
        public IActionResult UpdateMoveCommand(int id, int character_code, int stateGroup_code)
        {
            ViewBag.FormType = FormType.Update;
            ViewBag.readonly_Id = "readonly=\"readonly\"";
            ViewBag.TitleDescription = "기술명 수정 - 아래 항목을 수정하세요.";
            ViewBag.SaveButtonText = "수정";

            ViewBag.moveCommand = _moveCommandRepository.GetMoveCommandById(id);
            //ViewBag.tableName = TableName.move;
            //ViewBag.subTableName = TableName.move_Command;
            ViewBag.SelectStates = _stateRepository.GetSelectList();
            ViewBag.SelectStateGroups = _stateGroupRepository.GetSelectList(stateGroup_code);

            return View();
        }

        /// <summary>
        /// 기술 하위 분류 저장
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> UpdateMoveCommand(MoveCommand[] moveCommand)
        {
            _moveCommandRepository.Merge(moveCommand[0]); // 데이터 저장
            TranslateName[] translateName = new TranslateName[moveCommand.Length];
            for (int i = 0; i < moveCommand.Length; i++)
            {
                translateName[i] = new TranslateName(
                    TableName.move_Command,
                    moveCommand[i].Id,
                    moveCommand[0].Code,
                    moveCommand[i].Name,
                    moveCommand[i].Language_Code,
                    moveCommand[i].Change
                    );
            }

            UpdateAllName(translateName);
            //UpdateAllName()
            return RedirectToAction("Index", new { character_code = moveCommand[0].Character_code, movePosition = moveCommand[0].Code }); // 저장 후 리스트 페이지로 이동
        }

        /// <summary>
        /// 기술 하위 분류 저장
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> UpdateMoveCommandName(MoveCommand[] moveCommand)
        {
            _moveCommandRepository.UpdateMoveCommandName(moveCommand); // 데이터 저장
            return RedirectToAction("Index", moveCommand); // 저장 후 리스트 페이지로 이동

        }

        /// <summary>
        /// 기술 하위 분류 수정 폼
        /// <param name="code">code</param>
        /// </summary>
        [HttpGet]
        public override IActionResult UpdateName(int id)
        {
            ViewBag.TitleDescription = tableName;
            ViewBag.FormType = FormType.Update;
            ViewBag.SaveButtonText = "수정";

            TranslateName translateName = _translateNameRepository.GetTranslateNameById(id, TableName.move);

            return View(translateName);
        }

        [HttpPost]
        public String TransCommand(string command, string language_code)
        {
            return new TekkenCommand(command, language_code).GetResultcommand();
        }

        [HttpGet]
        public JsonResult GetKeyMap()
        {
            return Json(new TekkenCommand().GetKeyMaps());
        }

    }
}

TEKKEN_WEB/areas/Admin/Views/MoveCommand/Create.cshtml
@model MoveType

@{
    Layout = "_Layout";
}

<h2 style="text-align:center;">MoveCommand</h2>
@ViewBag.TitleDescription
<hr />

<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-controller="MoveCommand" asp-action="Create"
              enctype="multipart/form-data" method="post">
            @await Html.PartialAsync("_EditForm")
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

TEKKEN_WEB/areas/Admin/Views/MoveCommand/Index - 복사.cshtml
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["ReturnUrl"] = "~/Areas/MoveCommand";
}


<style>
    .table tbody tr:nth-child(4n-3) {
        background: #e2e2e2;
    }
</style>


<div class="container">
    <div class="m-auto" id="Character-list">
        <h2 style="text-align:center;">MoveCommand</h2>
        <span style="color: #ff0000">=================</span>

        <hr />
        @ViewData["MoveCommand"]

        @*==================== 캐릭터 코드 ====================*@
        <div class="row mb-3">
            <div class="col-sm-2">
                <label class="col-form-label col-form-label-sm">캐릭터</label>
            </div>
            <div class="col-sm">
                <select id="Character" asp-items="@ViewBag.SelectAllCharacters "></select>
                @*<input asp-for="Character_code" type="text" class="form-control form-control-sm" id="colFormLabelSm" placeholder="col-form-label-sm" readonly="readonly">*@
            </div>
        </div>

        <div class="table-responsive">
            <table class="table  table-bordered border-primary" style="width: 100%; margin-left: auto; margin-right: auto; border: 0;">
                <colgroup>
                    <col style="width: 20px;" />
                    <col style="width: 50px;" />
                    <col style="width: 50px;" />
                    <col style="width: 50px;" />
                    <col style="width: 100px;" />
                    <col style="width: 150px;" />
                    <col style="width: 100px;" />
                    <col style="width: 100px;" />
                    <col style="width: 150px;" />
                </colgroup>
                <thead class="table-dark">
                    <tr>
                        <th>@SharedLocalizer["Code"]</th>
                        <th>@SharedLocalizer["Move_name"]</th>
                        <th>@SharedLocalizer["Command"]</th>
                        <th>@SharedLocalizer["Modify"]</th>
                    </tr>
                </thead>

                <tbody class="table-light">

                    @{int idx = 0;}

                    @foreach (var item in ViewBag.GetAllMoves)
                    {

                        @if (idx % 3 == 0)
                        {
                            <tr>
                                <td>
                                    @Html.Raw(@item.Code)
                                </td>

                                <td>
                                    @Html.Raw(@item.Move_Name)
                                </td>

                                <td>
                                    @Html.Raw(@item.Command)
                                </td>
                                <td>
                                    <a asp-action="Update" class="btn btn-primary" asp-route-code="@item.Code" asp-route-character_code="@ViewBag.Character_Code">수정</a>
                                </td>
                                @ViewBag.Character_Code
                            </tr>
                        }
                        <tr>

                            <td>
                                @Html.Raw(@item.Language_Code)
                            </td>
                            <td>
                                @if (String.IsNullOrEmpty(@item.Name))
                                {
                                    <a asp-action="CreateName" class="btn btn-primary" asp-route-code="@item.Code" asp-route-languageCode=@item.Language_Code asp-route-name="@Html.Raw(@item.Move_Name)">추가</a>
                                }
                                else
                                {
                                    @Html.Raw(@item.Name)
                                }

                            </td>

                            <td>
                                <a asp-action="Update" class="btn btn-primary" asp-route-code="@item.Code">수정</a>
                            </td>
                        </tr>

                        idx++;
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>



@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <script>
        $('#Character').change(function () {
            var url = '/Admin/MoveCommand/Index';
            var character_code = $('#Character').val();
            location.href = url + '?Character_code=' + character_code;
        });

        $().ready(function () {
            var character_code = $('#Character').val();
            $('#Create').attr('href', '/Admin/MoveCommand/Create?Character_code=' + character_code)
            $('#Character').focus();
        });


    </script>
}

TEKKEN_WEB/areas/Admin/Views/MoveCommand/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    .table tbody tr:nth-child(5n-4) {
        background: #e2e2e2;
    }
</style>

<div class="container">
    @await Html.PartialAsync("_CharacterSelect")
    <label>@ViewBag.movePosition</label>
    @await Html.PartialAsync("_ListViewForm")
</div>



@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

<script>
        $('#Character').change(function () {
            var url = '/Admin/MoveCommand/Index';
            var character_code = $('#Character').val();
            location.href = url + '?Character_code=' + character_code;
        });

        $().ready(function () {
            var character_code = $('#Character').val();
            $('#Create').attr('href', '/Admin/MoveCommand/Create?Character_code=' + character_code)
            $('#Character').focus();

            var movePosition =@ViewBag.movePosition;
            if (movePosition > -1) {
                moveToPosition(movePosition);
            }
        });


</script>
}

TEKKEN_WEB/areas/Admin/Views/MoveCommand/Index2.cshtml
@inject IHtmlLocalizer<SharedResource> SharedLocalizer
@inject ITranslateNameRepository translateNameRepository

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["MoveCommand"] = "MoveCommand";
    ViewData["ReturnUrl"] = "~/Areas/MoveCommand";
}


<style>
    .table tbody tr:nth-child(4n-3) {
        background: #e2e2e2;
    }
</style>


<div class="container">
    <div class="m-auto" id="Character-list">
        <h2 style="text-align:center;">@ViewBag.TitleDescription</h2>

        <hr />
        @ViewData["MoveCommand"]

        @*==================== 캐릭터 코드 ====================*@
        <div class="row mb-3">
            <div class="col-sm-2">
                <label class="col-form-label col-form-label-sm">캐릭터</label>
            </div>
            <div class="col-sm">
                <select id="Character" asp-items="@ViewBag.SelectAllCharacters "></select>
                @*<input asp-for="Character_code" type="text" class="form-control form-control-sm" id="colFormLabelSm" placeholder="col-form-label-sm" readonly="readonly">*@
            </div>
        </div>

        <div class="table-responsive">
            <table class="table  table-bordered border-primary" style="width: 100%; margin-left: auto; margin-right: auto; border: 0;">
                <colgroup>
                    <col style="width: 20px;" />
                    <col style="width: 50px;" />
                    <col style="width: 50px;" />
                    <col style="width: 50px;" />
                    <col style="width: 100px;" />
                    <col style="width: 150px;" />
                    <col style="width: 100px;" />
                    <col style="width: 100px;" />
                    <col style="width: 150px;" />
                </colgroup>
                <thead class="table-dark">
                    <tr>
                        <th>@SharedLocalizer["Code"]</th>
                        <th>@SharedLocalizer["NUMBER"]</th>
                        <th>@SharedLocalizer["DESCRIPTION"]</th>
                        <th>@SharedLocalizer["Modify"]</th>
                    </tr>
                </thead>

                <tbody class="table-light">

                    @{int idx = 0;}

                    @foreach (var item in ViewBag.AllList)
                    {

                        @if (idx % 3 == 0)
                        {
                            <tr>
                                <td>
                                    @Html.Raw(@item.Code)
                                </td>

                                @*<td>
                                        @Html.Raw(@item.Move_Name)
                                    </td>*@

                                @*<td>
                                        @Html.Raw(@item.Command)
                                    </td>*@
                                <td>
                                    <a asp-action="Update" class="btn btn-primary" asp-route-code="@item.Code" asp-route-character_code="@ViewBag.Character_Code">수정</a>
                                </td>
                                @ViewBag.Character_Code
                            </tr>
                        }
                        <tr>

                            <td>
                                @Html.Raw(@item.Language_Code)
                            </td>
                            <td>
                                @if (String.IsNullOrEmpty(@item.Name))
                                {
                                    @*<a asp-action="CreateName" class="btn btn-primary" asp-route-code="@item.Code" asp-route-languageCode=@item.Language_Code asp-route-name="@Html.Raw(@item.Move_Name)">추가</a>*@
                                }
                                else
                                {
                                    @Html.Raw(@item.Name)
                                }

                            </td>

                            <td>
                                <a asp-action="Update" class="btn btn-primary" asp-route-code="@item.Code">수정</a>
                            </td>
                        </tr>

                        idx++;
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>



@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <script>
        $('#Character').change(function () {
            var url = '/Admin/MoveCommand/Index';
            var character_code = $('#Character').val();
            location.href = url + '?Character_code=' + character_code;
        });

        $().ready(function () {
            var character_code = $('#Character').val();
            $('#Create').attr('href', '/Admin/MoveCommand/Create?Character_code=' + character_code)
            $('#Character').focus();
        });


    </script>
}

TEKKEN_WEB/areas/Admin/Views/MoveCommand/UpdateMoveCommand.cshtml
@model MoveCommand

@{
    Layout = "_Layout";
}


<h2 style="text-align:center;">MoveCommand</h2>
<hr />

@*<div class="row">*@
<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-controller="MoveCommand" asp-action="UpdateMoveCommand"
              enctype="multipart/form-data" method="post">
            @await Html.PartialAsync("_EditForm")
        </form>
    </div>
</div>

@*<select asp-for="Code" asp-items="@ViewBag.SelectMoveType "></select>*@

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script type="text/javascript" src="~/js/command.js"></script>
    <script>TransCommand();</script>
}

TEKKEN_WEB/areas/Admin/Views/MoveCommand/UpdateName.cshtml
@{
    Layout = "_Layout";
}

<h2 style="text-align:center;">MoveCommandName</h2>
@ViewBag.TitleDescription
<hr />

@*<div class="row">*@
<div>
    <div class="col-md-offset-2 col-md-8 col-md-offset-2">
        <form asp-controller="MoveCommand" asp-action="UpdateName"
              enctype="multipart/form-data" method="post">
            @await Html.PartialAsync("_NameEditForm")
        </form>
    </div>
</div>


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

TEKKEN_WEB/areas/Admin/Views/MoveCommand/_EditForm.cshtml
@model MoveCommand[]
@using TEKKEN_WEB.Enums

<div class="row mb-3">
    <div class="col-3">
        <label asp-for="@Model[0].Code" class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col-9">
        <input asp-for="@Model[0].Code" type="text" class="form-control form-control-sm" value="@ViewBag.moveCommand[0].Code" placeholder="col-form-label-sm" readonly="readonly">
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-3">
        <label asp-for="@Model[0].Character_code" class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col-sm">
        <input id="Character_code" asp-for="@Model[0].Character_code" type="text" value="@ViewBag.moveCommand[0].Character_code" class="form-control form-control-sm" readonly="readonly">
    </div>
</div>

<div class="row mb-3">
    <div class="col-3">
        <label asp-for="@Model[0].Number" class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col">
        <input asp-for="@Model[0].Number" type="text" value="@ViewBag.moveCommand[0].Number" class="form-control form-control-sm" placeholder="col-form-label-sm" readonly="readonly">
    </div>
</div>

<div class="row mb-3">
    <div class="col-3">
        <label asp-for="@Model[0].Description" class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col">
        <input asp-for="@Model[0].Description" type="text" value="@ViewBag.moveCommand[0].Description" class="form-control form-control-sm" placeholder="col-form-label-sm" readonly="readonly">
    </div>
</div>

<div class="row mb-3">
    <div class="col-3">
        <label asp-for="@Model[0].Command" class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col-sm">
        <input id="Command" asp-for="@Model[0].Command" type="text" class="form-control form-control-sm" value="@ViewBag.moveCommand[0].Command" placeholder="col-form-label-sm" readonly="readonly">
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-2">  
        <label class="col-form-label col-form-label-sm"></label>
    </div>
    <div class="col-sm">
        <input id="displayCommand" type="text" class="form-control form-control-sm" placeholder="커맨드 입력" readonly="readonly">
    </div>
</div>
<br />

@{int i = 0; }
@foreach (var item in @ViewBag.moveCommand)
{
    <div class="row mb-1">
        <div class="col-1">
            <label asp-for="@Model[i].Id" class="col-form-label col-form-label-sm"></label>
        </div>
        <div class="col-2">
            <input asp-for="@Model[i].Id" class="form-control form-control-sm" value="@item.Id" readonly="readonly" />
        </div>
        <div class="col-1">
            <label class="col-form-label col-form-label-sm">Code</label>
        </div>
        <div class="col-2">
            <input asp-for="@Model[i].Language_Code" value="@item.Language_Code" class="form-control col-form-label-sm" readonly="readonly" />
        </div>

        <div class="col text-right">
            <div class="form-check">
                <input id="@String.Format("Change_{0}", @item.Language_Code)" asp-for="@Model[i].Change" class="form-check-input" type="checkbox">
                <label class="form-check-label" for="Change">
                    Modified
                </label>
            </div>
        </div>
    </div>
    <div class="row mb-1">
        <div class="col-1">
            <label class="col-form-label col-form-label-sm">AsIs</label>
        </div>
        <div class="col-11">
            <input type="text" class="form-control form-control-sm" value="@item.Name" placeholder="col-form-label-sm" readonly="readonly">
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-1">
            <label class="col-form-label col-form-label-sm">ToBe</label>
        </div>
        <div class="col-11">
            <input id="@String.Format("TlanslatedCommand_{0}", @item.Language_Code)" language_Code="@item.Language_Code" asp-for="@Model[i].Name" type="text" class="form-control form-control-sm commandName" placeholder="col-form-label-sm">
        </div>
    </div>
    i++;
}



<div class="row">
    <div class="col-sm-3">
        <button id="TransCommand" type="button" class="col btn btn-primary valid">변환</button>
    </div>
    <div class="col-sm-3">
        <input type="submit" value="@ViewBag.SaveButtonText" class="btn btn-primary" />
        <div class="col-sm-3">
        </div>
        <a asp-action="Index" class="btn btn-default" asp-route-character_code="@ViewBag.Character_Code">리스트</a>
    </div>
    @*<div class="col-sm">
            <a asp-action="Delete" class="btn btn-primary text-right" asp-route-id="@Model[0].Id" onclick="return confirm('정말 삭제하겠습니까?');">삭제</a>
        </div>*@

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <span class="text-danger">@ViewBag.ErrorMessage</span>
</div>





@*==================== 변환 커맨드 ====================*@
<!--<div class="row mb-3">
    <div class="col-sm-2">
        <label class="col-form-label col-form-label-sm">변환 커맨드 EN</label>
    </div>
    <div class="col-sm">
        <input id="TlanslatedCommand_en" type="text" class="form-control form-control-sm" placeholder="커맨드 입력" readonly="readonly"></input>
    </div>
</div>-->
@*==================== 변환 커맨드 ====================*@
<!--<div class="row mb-3">
    <div class="col-sm-2">
        <label class="col-form-label col-form-label-sm">변환 커맨드 KO</label>
    </div>
    <div class="col-sm">
        <input id="TlanslatedCommand_ko" type="text" class="form-control form-control-sm" placeholder="커맨드 입력" readonly="readonly"></input>
    </div>
</div>-->
@*==================== 변환 커맨드 ====================*@
<!--<div class="row mb-3">
    <div class="col-sm-2">
        <label class="col-form-label col-form-label-sm">변환 커맨드 JP</label>
    </div>
    <div class="col-sm">
        <input id="TlanslatedCommand_jp" type="text" class="form-control form-control-sm" placeholder="커맨드 입력" readonly="readonly"></input>
    </div>
</div>-->
@*==================== 기술 상태 입력 ====================*@
<div class="row mb-3">
    <div class="col-sm-2">
        <label class="col-form-label col-form-label-sm">States Group</label>
    </div>
    <div class="col-sm">
        <select id="StateGroup" asp-items="@ViewBag.SelectStateGroups"></select>
    </div>
</div>

<div class="row mb-3">
    <div class="col-sm-2">
        <label class="col-form-label col-form-label-sm">States</label>
    </div>
    <div class="col-sm">
        <div id="State">
        </div>
    </div>
</div>





<!-- Modal placeholder -->
<div id="modal-placeholder"></div>